### ISSUE TITLE
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by mohit-choithwani** [chinhsuanwu/ifusion#4]
Hi, I am getting the following error while running the demo.
`[INFO] Loading Zero123...
[INFO] Loading model from ldm/ckpt/zero123-xl.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.53 M params.
Keeping EMAs of 688.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
100%|████████████████████████████████████████| 890M/890M [00:08<00:00, 105MiB/s]
[INFO] Loaded Zero123
[INFO] Pose optimization
[INFO] Loading image asset/sorter/0.png
[INFO] Loading image asset/sorter/1.png
  0%|                                                                                                                                                | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/tt/models/ifusion/main.py", line 28, in <module>
    main(config)
  File "/home/tt/models/ifusion/main.py", line 12, in main
    optimize_pose(model, **config.pose)
  File "/home/tt/models/ifusion/ifusion.py", line 145, in optimize_pose
    pose = optimize_pose_pair(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tt/models/ifusion/ifusion.py", line 93, in optimize_pose_pair
    total_loss, theta, azimuth, distance = optimize_pose_loop(
                                           ^^^^^^^^^^^^^^^^^^^
  File "/home/tt/models/ifusion/ifusion.py", line 41, in optimize_pose_loop
    T_delta = SE3.exp(xi).as_matrix()
              ^^^^^^^^^^^
  File "/home/tt/anaconda3/lib/python3.11/site-packages/liegroups/torch/se3.py", line 85, in exp
    rho.unsqueeze_(dim=2)
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.
` 
Could you please advise me on what steps to take inorder to solve this?
Thank you;)

**Comment by chinhsuanwu** [comment]
You are using the original [liegroups](https://github.com/utiasSTARS/liegroups) implementation, which does not support gradient descent. Please install the [modified version](https://github.com/chinhsuanwu/liegroups) by running

```bash
pip install git+https://github.com/chinhsuanwu/liegroups.git
```

**Comment by mohit-choithwani** [comment]
```shell
> pip install git+https://github.com/chinhsuanwu/liegroups.git
```

Thanks a lot! This solution did the trick for me.
